### ISSUE TITLE
"Normal mouse pointer" tool is weird

### ISSUE THREAD

**Issue by bertob** [SjoerdB93/Graphs#109]
All the other tools are a mode of interacting with the graph, but this one seems to just do nothing, so I'm not sure why it's needed.

![image](https://user-images.githubusercontent.com/1908896/217406010-14c82c14-7b4c-4e04-95a5-368c0b0428d2.png)

**Comment by SjoerdB93** [comment]
While I've considered the point that this mode does literally nothing, that is kind of the idea of this mode. To have some sort of neutral mode, where mouse clicks and actions are "safe" and don't do anything. Like a way to turn off all other modes. I am open to removing it if that's considered better, as the same result can be achieved by simply not clicking on the Graph, and there's not much point to wanting to click on the Graph in Normal pointer mode either.

**Comment by bertob** [comment]
> the same result can be achieved by simply not clicking on the Graph, and there's not much point to wanting to click on the Graph in Normal pointer mode either.

Other toolbox apps (e.g. GIMP, Inkscape, and the like) don't have a "do nothing" mode as far as I'm aware. It's usually select, move, or some drawing tool I think.

My feeling is that the "neutral" mode in this case could be either move or select, depending on which one you think is more frequently used. Neither of the modes is destructive, so I don't think it'd be weird for them to be on by default.

**Comment by SjoerdB93** [comment]
I've been using Inkscape quite a lot today (for graphing purposes actually), and indeed all modes actually specifically do something. Even the "mouse pointer mode" is used for selection and transformation of objects. I think it's a fair point that such a neutral mode is not consistent with that kind of design at least. 

I've opened a PR to go back to three different modes.
![image](https://user-images.githubusercontent.com/68477016/217917594-39a7cd22-8b52-430b-9e1f-864bd4f5b5e2.png)

I can merge it later, but I'll test it a bit more to see if there's no unintended bugs.
