### ISSUE TITLE
New icon?

### ISSUE THREAD

**Issue by bertob** [SjoerdB93/Graphs#11]
The current icon doesn't follow the GNOME icon guidelines, would you like help with a new one?

Here's a first attempt:

![image](https://user-images.githubusercontent.com/1908896/211640724-2a7ebd12-df82-44b6-b272-b257a6cfdf64.png)

**Comment by SjoerdB93** [comment]
Hi,

That's highly appreciated, and indeed fits much nicer with the GNOME icon guidelines, which I had only read after making an icon.
Your attempt looks very nice. and I prefer it over the current logo. If I'd want to add something, I think the line itself should be behind the axis maybe. 

But I'd happily accept help with a new icon, and this looks very nice.

**Comment by bertob** [comment]
Cool, I fixed the line overlap and opened an MR :)
