### ISSUE TITLE
Better tool category names

### ISSUE THREAD

**Issue by bertob** [SjoerdB93/Graphs#110]
"Adjust Data" and "Manipulate Data" are very similar, it'd be good to have more distinct names for the tool categories.

**Comment by SjoerdB93** [comment]
Yes, I think these category names could use some improvements. Perhaps something like "Adjust Data" and "Transform Data", but that's just thinking out loud right now.

The biggest divide between these categories at least is that "Adjust Data" just moves data around a bit, or in the most extreme case cuts part away.  The "Manipulate Data" section has actual mathematical operations being applied on them that are fundamentally distinct from just moving stuff around.

**Comment by bertob** [comment]
Maybe "Mathematical Operations" could be a good name for the second section then?
