### ISSUE TITLE
Better empty state for data panel

### ISSUE THREAD

**Issue by bertob** [SjoerdB93/Graphs#128]
It's great that there's an empty state here now, but it could be even better. I'd try a status page (I think there's a style class to make it smaller than normal, though I don't remember what it's called) with a layout in this direction:

```
                 [ chart icon ]
                    No Data

Add data from a file or manually as an equation 
```

Icon: ![graph2-symbolic](https://user-images.githubusercontent.com/1908896/217956603-caa94008-d727-431d-b89e-2395e52003e8.svg)

I don't think it's necessary to reference the button in the top left, that should be fairly obvious.

![image](https://user-images.githubusercontent.com/1908896/217955247-53b8bf7a-915b-4a3a-8b2e-e535fae0239f.png)

**Comment by SjoerdB93** [comment]
Thanks, I didn't know about the existence of AdwStatusPage!

> I think there's a style class to make it smaller than normal, though I don't remember what it's called

You're right, it's in [the docs](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.StatusPage.html):  "AdwStatusPage can use the [.compact](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/style-classes.html#compact-status-page) style class for when it needs to fit into a small space such a sidebar or a popover."

**Comment by SjoerdB93** [comment]
I'm not sure if it's possible to give subtitles to an AdwStatusPage, right now I've just added a GtkLabel as child to the status page for the subtext. It looks like this, will put it up on a new branch.

![image](https://user-images.githubusercontent.com/68477016/218099726-a02f2dc8-9a4c-4dbc-a617-d804011c6b96.png)

**Comment by SjoerdB93** [comment]
You were right, it's indeed the description property. The margins look better also than adding a GtkLabel below.
The compact style is definitely being applied correctly it seems, there's a significant difference.

Without the compact styling:
![image](https://user-images.githubusercontent.com/68477016/218102724-b11ae8c2-0c4a-4898-ba97-737a08cdb8dd.png)

With the compact styling:
![image](https://user-images.githubusercontent.com/68477016/218102901-013d83a4-5a1c-473a-93a5-e3dff819c938.png)

**Comment by bertob** [comment]
Hmm, this still feels too big. Might also be the icon, maybe something more subdued would be better here, e.g. `table-sybmolic` from devkit?

Also, the description feels a bit wide, a narrower column width would probably help.

**Comment by SjoerdB93** [comment]
Here's a narrower column width combined with `table-symbolic`:
![image](https://user-images.githubusercontent.com/68477016/218113145-e63a2a1a-8c54-4360-b1b9-c8899f9238d8.png)

And here's `graph-symbolic`.
![image](https://user-images.githubusercontent.com/68477016/218113196-e6d49621-e67e-4702-a5a8-808d88755585.png)

I'm not 100% sure which one I prefer. Without looking, I'd say the graphs one would be more appropriate. But having tested both, I'm not too convinced it's the better one.

**Comment by cmkohnen** [comment]
Throwing something different in the mix: how about list-compact (left) or list-symbolic(right):
![grafik](https://user-images.githubusercontent.com/59118042/218142051-2cc25ac0-78d7-4713-af4f-e966de959438.png)

**Comment by SjoerdB93** [comment]
Just for reference, here's list-symbolic:
![image](https://user-images.githubusercontent.com/68477016/218142800-067abf31-0d18-49f1-ab72-39feb9cb8eb7.png)

And list-compact-symbolic:
![image](https://user-images.githubusercontent.com/68477016/218142932-469658df-f004-4746-ae0b-16ee3bfd1804.png)

**Comment by bertob** [comment]
> And list-compact-symbolic

This looks pretty good to me :+1:

**Comment by SjoerdB93** [comment]
> This looks pretty good to me +1

Yeah, it works quite well as a symbolic version of the data list that we have up there when something **is** loaded. So this was a nice suggestion that I was not even thinking about before @cmkohnen brought it up. I merged this now.
