### ISSUE TITLE
Proper snake case

### ISSUE THREAD

**Issue by cmkohnen** [SjoerdB93/Graphs#148]
Currently we got into conflict multiple times regarding capitalization throughout the code base.
my suggestion would be to properly go through the entire codebase after tackling the currently open prs and applying one form or the other.
The proper way should be all lowercase, without any uppercase letters save classnames. This might break existing saved projects, but as they aren't part of any release yet, this shouldn't be an issue, especially since everything in future releases will then be named "correctly".
If there are any reasons against this I'm all ears

**Comment by SjoerdB93** [comment]
Yeah agreed, above all this should be handled consistently. Going lowercase, except classes is the convention. Breakage of saved projects during development is to be expected, as long as we make sure not to break anything between releases.
