### ISSUE TITLE
Proposal: Plot Styles

### ISSUE THREAD

**Issue by cmkohnen** [SjoerdB93/Graphs#160]
I was thinking about a way to handle graph presets and came up with an idea. 

**Plot Styles**
The user can only choose between predefined styles and cannot change things like tick length etc. on the fly. Plot Settings should only be related to things like labels, scaling, whether to use a legend etc. (stuff that is "content"-related) and changing the style. Somewhere we should expose a style editor. In there the user should be able to edit styles in depth. Some styles should be fixed, like default matplotlib and our adwaita ones. To edit these a copy-function would be ideal. 

Since matplotlib registers styles from the users config directory this should be doable. Another idea might be to set the matplotlib config dir to something inside the graphs config dir, as to avoid confusion regarding their save location down the line.
This would also keep a few things out of the config file, where we just store which style should be used by default.

I am open for feedback or suggestions. But I do think that this enables more freedom in customizing the graph and benefits the general app design

**Comment by SjoerdB93** [comment]
Yes, just using the predefined matplotlib styles as now is not super ideal anyway, and in most cases you really don't need to change tick length and width. However given it's exposed quite easily in matplotlib, I do think having the option to change this is quite nice.

Moving these customization towards a style editor would be a cleaner solution in the end, cleaning up the settings and make it easier to save certain styles for later use. In that case it would certainly make sense to move the matplotlib config to such a config file. So I'm in favour of this on all accounts.
