### ISSUE TITLE
Confusing "Config not found" message on first startup

### ISSUE THREAD

**Issue by jannuary** [SjoerdB93/Graphs#19]
First thing the app greets you with is an error message saying something along the lines of "config not found, creating one"

This seems really weird to show when one has just installed the app – of course it wouldn't be found in that case.

**Comment by SjoerdB93** [comment]
Good point.

Each time when starting the application, it looks for a config file and if it doesn't find one it creates a new one from template and displays said message. But perhaps it's better to either change the wording, e.g. "Creating new config file", or remove the message as a whole. Will look into this.

**Comment by SjoerdB93** [comment]
By the way, if you do have an opinion on preferred behaviour, please let me know, I'm always willing to listen :)
I'm tempted to just change the wording, such that it doesn't look like something went wrong.

**Comment by jannuary** [comment]
I'd just remove it — it doesn't seem relevant and isn't really done elsewhere.

**Comment by SjoerdB93** [comment]
I think this latter is a fair point, that this is not really standard behaviour.

In fact, now I think of it, it's quite common behaviour to just create a new config file without informing the user about it whenever the old one gets deleted. So I'll probably just do that, remove the message.

Thanks a lot for the feedback!
