### ISSUE TITLE
UI: Use GNOME icons

### ISSUE THREAD

**Issue by TheEvilSkeleton** [SjoerdB93/Graphs#32]
I noticed the toolbar does not use GNOME icons:

![image](https://user-images.githubusercontent.com/50847364/215273772-f6993eda-aaaf-4e05-96dd-1856cda3fc7d.png)

I suggest to use GNOME icons whenever possible, as they look more familiar and better on GNOME. I recommend using [Icon Library](https://apps.gnome.org/app/org.gnome.design.IconLibrary/).

**Comment by SjoerdB93** [comment]
Thanks a lot for the heads-up. Indeed it would be nicer to use the GNOME icons, when making the toolbar icons I didn't consider there may be existing icons out there that I could use. I will swap them out, seems I have a good alternative for all of them in the Icon Library.

**Comment by SjoerdB93** [comment]
Fixed with PR #39
