### ISSUE TITLE
Make graphs list sidebar retractable

### ISSUE THREAD

**Issue by mossymossmoss** [SjoerdB93/Graphs#36]
Making the graphs list sidebar retractable would make it so that you can still use the app when the window is scaled down horizontally, as currently it just disappears entirely
![image](https://user-images.githubusercontent.com/56167669/215284220-5602c5d0-b89b-4f00-8842-6ef09e1c159d.png)

It would also allow you to get rid of the "Open In New Window" button, as you would be providing the user with essentially the same view
![image](https://user-images.githubusercontent.com/56167669/215284186-f1365e20-73b3-463d-aaba-edc7c7607991.png)
![image](https://user-images.githubusercontent.com/56167669/215284199-08210462-e792-41c0-a818-a422bafc0d40.png)

**Comment by cmkohnen** [comment]
I have actually tried to implement this about a week ago.
The foundation to do this already exists, since the sidebar is currently using libadwaitas Flap, which takes away ~50% of the work needed.
I'll try tackling this in the next few days.

**Comment by SjoerdB93** [comment]
@cmkohnen Thanks, I also played around trying to achieve the same thing after you implemented the Libadwaita Flap, but my attempts didn't work out. So it was indeed on the list of things that should be done.
