### ISSUE TITLE
Use dynamic axis step sizes when adjusting plot width

### ISSUE THREAD

**Issue by mossymossmoss** [SjoerdB93/Graphs#37]
It appears as if there is logic to assign a new axis step size when zooming in on a certain area (picture here is a random example of the result of a zoom in)
![image](https://user-images.githubusercontent.com/56167669/215284451-d15968ec-8cf0-4218-8bff-b4abd86442cc.png)

It would make sense if this was automatically adjusted to be a greater size when shrinking the window, such that there are less labelled steps and you can show the full axis
![image](https://user-images.githubusercontent.com/56167669/215284508-fef9e3e5-6e7a-4fb3-8c75-d219aaaea67b.png)

Pictured here is the result of reducing the window width in Plots
![image](https://user-images.githubusercontent.com/56167669/215284583-f0a9158f-4771-498e-95a3-478ccf5e88b3.png)
![image](https://user-images.githubusercontent.com/56167669/215284564-4db18d4a-c550-4d87-932b-fa0aa1b36659.png)

**Comment by SjoerdB93** [comment]
Just for clarity's sake. The suggestion is to change the step size used when shrinking the window?

All graphing functionalities are driven by the matplotlib module. I'll take a look in their documentation, but I'm not 100% sure how flexible this behaviour is.

**Comment by cmkohnen** [comment]
Since we are no longer embedding the graph in a scrollview, the graph scales now correctly. If changing to a small size, matplotlib automatically adjusts step-size as requested. However the current maximum is 5 steps and it will only fall down to 3 (or 2) if not enough space is available to display all labels

**Comment by cmkohnen** [comment]
Forget my last comment, it scales on a few other factors as well, and can go over five markers.
