### ISSUE TITLE
PIP doesn't update when adding new data

### ISSUE THREAD

**Issue by cmkohnen** [SjoerdB93/Graphs#48]
As the title says.
Opening a PIP-window and adding data doesn't update tha graph inside the PIP window.

**Comment by SjoerdB93** [comment]
Yeah, the thing is that the pip window gets rendered on it's own canvas, and all actions are plotted on the original canvas. It is probably possible to just refactor self.canvas towards a list that contains all canvases, and each time we plot on this canvas, we just loop over all these canvases. That does feel pretty ugly though. 

I think we should also consider the option to just remove the button as well, as suggested in issue #36, given retracting the sidebar has the same effect. I'm not 100% decided on this.
