### ISSUE TITLE
Use recoloring for symbolics

### ISSUE THREAD

**Issue by bertob** [SjoerdB93/Graphs#50]
I was just looking at the icons and noticed that the app ships duplicate dark/light versions. That's should not be necessary, GTK can recolor symbolics if the name ends in `-symbolic`.

**Comment by SjoerdB93** [comment]
Yes, that indeed works perfectly well when defining the icon in the ui file. However the toolbar class from matplotlib (which the toolbar here inherits from) wants a direct path to the icon. 

So the toolbar is defined a such: 
```
class GraphToolbar(NavigationToolbar):

    def __init__(self, canvas, parent):
        self.parent = parent
        path = os.path.join(os.getenv("XDG_DATA_DIRS"))
        path = path.split(":")[0] + "/graphs/graphs/icons"

        if Adw.StyleManager.get_default().get_dark():
            dark = "-dark"
        else:
            dark = ""
        backwards_button = f"{path}/arrow1-left{dark}"
        forwards_button = f"{path}/arrow1-right{dark}"
        home_button = f"{path}/go-home{dark}"
        zoom_button = f"{path}/loupe{dark}"
        save_button = f"{path}/document-save{dark}"
        move_button = f"{path}/move-tool{dark}"
        xscale_button = f"{path}/change-xscale{dark}"
        yscale_button = f"{path}/change-yscale{dark}"
        plot_settings_button = f"{path}/settings{dark}"
        PIP_button = f"{path}/pip-in{dark}"

        self.toolitems = (
            ('Home', 'Restore original view', home_button, 'set_canvas_limits'),
            ('Back', 'Previous view', backwards_button, 'back'),
            ('Forward', 'Next view', forwards_button, 'forward'),
            (None, None, None, None),
            ('Pan', 'Left button to pan, right button to zoom. Hold control to to keep aspect ratio fixed', move_button, 'pan'),
            ('Zoom', 'Zoom to rectangle', zoom_button, 'zoom'),
            ("ChangeYScale", "Change Y-scale", yscale_button, "change_yscale"),
            ("ChangeXScale", "Change X-scale", xscale_button, "change_xscale"),
            ("Settings", "Plot Settings", plot_settings_button, "load_plot_settings"),
            (None, None, None, None),
            ('PIP', 'Open in New Window', PIP_button, 'open_pip_mode'),
            ('Save', 'Save figure', save_button, 'save_figure'),
        )
        super().__init__(canvas, parent)
```
Where toolitems defines the icons that rest on each toolbar. The arguments on each row are the name of the item, the tooltip, the path to the icon, and the function to be executed when presing on the icon. As far as I understood, giving the path to the icon is the only way to do this, it only accepts regular strings. Using e.g.  `"move-tool"` directly just gives a broken icon as it just takes the input string as location. But I could be misinterpreting here, the navigationtoolbar class is not that well-documented.

 I _think_  this is an upstream issue in Navigationtoolbar. But if it is actually possible to use these icons directly, I'd be glad to hear that. As that'd be much cleaner than hard-coding the icons in like this.

**Comment by bertob** [comment]
Aha, interesting! I guess it'd be good to file the bug upstream then, yeah.
