### ISSUE TITLE
Symbolic updates

### ISSUE THREAD

**Issue by bertob** [SjoerdB93/Graphs#51]
Improved icons for a few of the toolbar ones (these are all in devkit now, but not yet in Icon Library):

![image](https://user-images.githubusercontent.com/1908896/215555856-83aa4be4-8697-48ac-a6eb-6e305865ac94.png)

![axis-log-horizontal-symbolic](https://user-images.githubusercontent.com/1908896/215553158-30bbe2a0-7775-4c5c-b517-d1424eb671cc.svg)

![axis-log-vertical-symbolic](https://user-images.githubusercontent.com/1908896/215553165-7547c33c-f3fe-4999-9d52-141f77393e80.svg)

![pip-out-symbolic](https://user-images.githubusercontent.com/1908896/215553790-a2656567-32c3-4ab2-b10f-560fea04a180.svg)

Also, in the plot settings view switcher I'd use different icons:

![image](https://user-images.githubusercontent.com/1908896/215555077-de124976-ebd7-4111-a921-b3d048e98658.png)

Lines: 
![function-third-order-symbolic](https://user-images.githubusercontent.com/1908896/215555760-44f0e02d-eb70-45e9-bcfe-27f8ddc84fed.svg)

Axes: 
![move-tool-symbolic](https://user-images.githubusercontent.com/1908896/215555543-fdaadcdb-a40b-43f5-916b-065c272d2053.svg)

**Comment by cmkohnen** [comment]
As the suggested icons contain only "LOG" it would be a nicer solution to have the two respective buttons as togglebuttons (likewise actions such as the move tool and zoom feature and maybe even pip).
A solution would be to rewrite the toolbar without the matplotlib backend, as this would mitigate https://github.com/SjoerdB93/Graphs/issues/50 and give us more flexibility.

**Comment by bertob** [comment]
> As the suggested icons contain only "LOG" it would be a nicer solution to have the two respective buttons as togglebuttons

That would be nicer, but I thought it's maybe clear enough from context/tooltip that it switches between linear and logarithmic. But yeah, moving away from the matplotlib thing seems like a good direction regardless.

**Comment by SjoerdB93** [comment]
> A solution would be to rewrite the toolbar without the matplotlib backend, as this would mitigate https://github.com/SjoerdB93/Graphs/issues/50 and give us more flexibility.

I was thinking of the same thing on my way home today. It makes sense to keep using matplotlib for the graphing capabilities, it's a very powerful module that is well supported and the defacto standard for plotting in Python world, but this toolbar has its problems and is also not really well-documented. 

I think moving away from it would make a lot of sense and would help Graphs in the long run. I'd have to look how to get certain actions (specifically the zoom and pan toggles) in a custom toolbar, but that should be doable. Matplotlib itself is well-documented also.

**Comment by cmkohnen** [comment]
Just a heads up, I'm currently trying to rewrite this and it seems doable by using a sort of "dummy" toolbar
