### ISSUE TITLE
Save button is too prominent

### ISSUE THREAD

**Issue by bertob** [SjoerdB93/Graphs#53]
The "Save" button in the top right is too prominent for the main window. I'd either go with a symbolic icon and no `.suggested` styling, or maybe just move it to the primary menu altogether, since there's not that much stuff in there currently.

![image](https://user-images.githubusercontent.com/1908896/215557420-f9ca9599-2e0f-4731-b8e2-32cc097eed39.png)

**Comment by cmkohnen** [comment]
https://github.com/SjoerdB93/Graphs/pull/49 includes a change, that moves the button into the primary menu
