### ISSUE TITLE
Increase padding on equation rows

### ISSUE THREAD

**Issue by bertob** [SjoerdB93/Graphs#58]
The current padding on the equation rows looks a bit cramped, quick inspector hack to fix it:

![image](https://user-images.githubusercontent.com/1908896/215742937-7ee1acea-dea3-4496-b6d4-22ddfebcdd90.png)

**Comment by SjoerdB93** [comment]
That does look more comfy and nice overall. Think some extra padding would be nice indeed, especially if we can combine it with a smaller color chooser button.
