### ISSUE TITLE
Rethink Cut placement

### ISSUE THREAD

**Issue by bertob** [SjoerdB93/Graphs#61]
I'm still not sold on the "cut" action being added to the primary tools. Even if it has a different scope from other actions, it makes more sense to me to group it into one of the categories than having it bolted onto the selection button.

![image](https://user-images.githubusercontent.com/1908896/215919827-50961109-98ab-4687-aa5c-f72ca081e096.png)

How about this: We add the button to the bottom of the first group, but have a very explicit label explaining the scope, e.g. "Cut Points in Selection" and have the button disabled when there's no selection.

**Comment by SjoerdB93** [comment]
I'm pretty open to moving it to the first group. Mostly because it's quite distinct from these toolbar options. Reset, pan and zoom are all tools to interact with the plot view. Select and cut is a way to manipulate the data. So i see the argument of moving it.

We could still make the but button contextually appear,  with "select and cut" as label but I think that would make the button too wide so just disabling it when you can't use it is probably a better solution.

**Comment by SjoerdB93** [comment]
Looking at the "Adjust Data" group. Adding this one there would provide an odd amount of items, which will look awkward in a 2-column grid panel. One option would be to add it as a 2-column wide row, giving it plenty of space to expand with a contextual cutting symbol upon activation, while having the label "Select and cut".  

I'll may experiment with it this evening or so after work.

**Comment by bertob** [comment]
I was just thinking, if "Cut" is the only thing you can actually do with the selection, perhaps it doesn't make sense to have "Select" as a distinct action and it should just be a single "Select and Cut" action where you click the button, do the selection, and it deletes those nodes?

**Comment by bertob** [comment]
> However, I've been working on an implementation of having all actions applied to only the selected area when Selection mode is activated. See PR https://github.com/SjoerdB93/Graphs/pull/65. If we decide to implement that behaviour, I think it makes sense to have Selection mode as it's own mode, and move the cut action to the top group ("Adjust data"), and just deactivating the button when not in selection mode..

That makes sense, yeah. In that case the 3 tools/modes idea from #62 would work cleanly.

**Comment by SjoerdB93** [comment]
Yes exactly. Then for the "reset view" button, we can probably have it only in the "View" menu (the one next to the primary menu) and couple it to a keyboard shortcut as @cmkohnen suggests, coupling keyboard shortcuts to an action is quite trivial to do. 

Then these three modes would work nicely with a StackSwitcher. While the mock-up you present at Gitlab looks beautiful, I'm not sure how easy it is to implement just now given it's not an existing GTKWidget, and I don't know where to start implementing a widget like so. So we could (mis)use the existing StackSwitcher widget to get a very similar effect, and just not let it actually change a stack/view, but just use it to indicate the current mode of operation.

For this specific issue. If we do it like that, then I think we can just move the "Cut" button to the "Adjust Data" section, and perhaps disable it when not in selection mode. That should overall give a pretty coherent behaviour.
