### ISSUE TITLE
No white surfaces (apart from external media etc)

### ISSUE THREAD

**Issue by cmkohnen** [SjoerdB93/Graphs#89]
Resizing the graph currently shows a white background even in dark mode, this should be changed

**Comment by SjoerdB93** [comment]
I think the issue is that Matplotlibs FigureCanvas tries to redraw immediately each time the window is resized. I've gotten the entire widget to hide when it's being resized by connecting a hide() function to the `resize`  signal of the widget. Unfortunately I don't know how to get it back again.

Best would probably to get it to stop redrawing completely while the window is being resized, and enable this behaviour again when we stop resizing but I'm not sure yet if this is possible or how. There's some hacky ideas I'll may try tomorrow but not sure if I'll find a great solution.

**Comment by SjoerdB93** [comment]
So I think this is an upstream Matplotlib issue, here's a minimal reproducible example using purely matplotlib:

```
import numpy as np
import matplotlib.pyplot as plt


plt.style.use('dark_background')

fig, ax = plt.subplots()

L = 6
x = np.linspace(0, L)
ncolors = len(plt.rcParams['axes.prop_cycle'])
shift = np.linspace(0, L, ncolors, endpoint=False)
for s in shift:
    ax.plot(x, np.sin(x + s), 'o-')
ax.set_xlabel('x-axis')
ax.set_ylabel('y-axis')
ax.set_title("'dark_background' style sheet")

plt.show()
```

See attached screencast as well. I'll try and ask around in Python/matplotlib circles if it's possible to stop Matplotlib from redrawing while the window is being resized, but I'm not sure about this. This could be that it's some GTK thing to redraw widgets upon resizing, which happens to be matplotlib in this case.

I guess the workaround again would be to hide the widget when resizing and showing it again while not resizing. Perhaps it's possible the change this white background we get to black (which I guess would be a matplotlib thing again), but I would not really know how. I will keep this issue open, and ask around to see if there's something that can be done.

**Comment by SjoerdB93** [comment]
Indentation didn't really work on pasting it on the terminal, so the lines where not shown, here's a screencast where I just open a script with the same example code:

[Screencast from 2023-02-08 09-28-32.webm](https://user-images.githubusercontent.com/68477016/217475638-69a360c1-d868-4c1c-aa59-b4158b1b2c0a.webm)

**Comment by SjoerdB93** [comment]
Here's a screencast of the general problem described in this issue, just for reference:

[Screencast from 2023-02-08 09-37-47.webm](https://user-images.githubusercontent.com/68477016/217477919-c10450e0-0c7e-4a42-b54a-d961d02892e4.webm)

**Comment by SjoerdB93** [comment]
So I've puzzled a bit more, and I'm now pretty sure this is an issue with the GTK backend. I've got another application (a data reduction tool for GISAXS measurements), which is written with Qt, and that doesn't have this issue.

[Screencast from 2023-02-08 11-48-42.webm](https://user-images.githubusercontent.com/68477016/217508956-7680cbd2-7b5b-4068-b931-14ed34051883.webm)

**Comment by SjoerdB93** [comment]
And boom, won't you look at that, using the `backend_gtk4cairo` backend instead! (See video)
Thanks for filing this issue, as I suspected this was pretty much not reasonably fixable.

[Screencast from 2023-02-08 11-59-30.webm](https://user-images.githubusercontent.com/68477016/217511220-46590138-cb55-4394-8ab4-9272250b0222.webm)
