### ISSUE TITLE
High-contrast mode works

### ISSUE THREAD

**Issue by cmkohnen** [SjoerdB93/Graphs#90]
Button Icons don't work in high contrast

**Comment by cmkohnen** [comment]
Apparently most non-custom icons are broken. This includes the edit icon in entry rows and most button icons. I do belive this is an upstream bug, but I'm not quite sure

**Comment by SjoerdB93** [comment]
Interestingly enough, it indeed seems mostly the non-custom ones. At the current implimentation of PR #115, it's just the mouse icon and the edit icons in the entry rows. Will try to investigate a bit more, before definitely concluding it's an upstream thing. But it does seem that way.

![image](https://user-images.githubusercontent.com/68477016/217571767-aeb73390-46a1-427a-8730-2089f00f3aef.png)

**Comment by cmkohnen** [comment]
I wouldn't consider this a blocker for 1.5 as this no longer effects the mouse pointer, which has been removed

**Comment by SjoerdB93** [comment]
Yeah I've been quite busy this week so unfortunately haven't had much time to look at this among others, but I don't think it should be a blocker for 1.5 either. I will keep this up as long as I haven't confirmed it's an upstream GTK bug.

**Comment by SjoerdB93** [comment]
So this is a thing in Gnome Builder, if you actually opened an installed Flatpak they icons work perfectly fine:

![image](https://user-images.githubusercontent.com/68477016/219662838-9469e3bf-5bbe-4f1d-b870-2f6038c98dbf.png)
